[package]
name = "maxbib"
version = "0.1.0"
authors = ["Max Tyler <maxastyler@gmail.com>"]
edition = "2018"

[dependencies]
tui = "0.5.0"
termion = "1.5.1"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.8"
rff = "0.3.0"
glob = "0.2"
clap = "2.3"